// Mocks generated by Mockito 5.0.10 from annotations
// in clean_architeture_flutter/test/data/usecases/local_load_current_user_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:clean_architeture_flutter/app/data/cache/fetch_shared_preferences.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [FetchSharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchSharedPreferences extends _i1.Mock
    implements _i2.FetchSharedPreferences {
  MockFetchSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> fetch(String? key) =>
      (super.noSuchMethod(Invocation.method(#fetch, [key]),
          returnValue: Future<String?>.value()) as _i3.Future<String?>);
}
